# Generated by Django 3.2.10 on 2021-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disanswer',
            name='image',
            field=models.ImageField(default='models/answer.jpg', null=True, upload_to='media/DisCussion'),
        ),
    ]
