# Generated by Django 3.2.10 on 2021-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disanswer',
            name='image',
            field=models.ImageField(default='models/answer.jpg', null=True, upload_to='media/discussion-pics'),
        ),
    ]
