# Generated by Django 3.2.10 on 2021-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0004_alter_disanswer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disanswer',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disanswer',
            name='image',
            field=models.ImageField(default='media/answer.jpg', null=True, upload_to='media/discussion-pics'),
        ),
    ]
