# Generated by Django 3.2.10 on 2021-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211218_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/blogindex.jpg', null=True, upload_to='media/blog-pics'),
        ),
    ]
