# Generated by Django 4.0 on 2022-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/blogindex.jpg', null=True, upload_to='blog-pics'),
        ),
    ]
